ERP/CRUD/urls.py
from django.urls import include, path
from . import views
from rest_framework.routers import DefaultRouter

app_name = "CRUD"

router = DefaultRouter()
router.register('assets', views.AssetViewSet)

urlpatterns = [
	path("", views.CRUD_home, name="CRUD_home"),
	path("create/", views.CRUD_create, name="CRUD_create"),
	path("retrieve/", views.CRUD_retrieve, name="CRUD_retrieve"),
	path("delete/<int:id>", views.CRUD_delete, name="CRUD_delete"),
	path("update/<int:id>", views.CRUD_update, name="CRUD_update"),
    path('consultar_estoque/', views.consultar_estoque_view, name='consultar_estoque'),
	path('adicionar_estoque/', views.adicionar_estoque_view, name='adicionar_estoque'),
    path('remover_estoque/', views.remover_estoque_view, name='remover_estoque'),
    path('atualizar_estoque/', views.atualizar_estoque_view, name='atualizar_estoque'),
    path('atualizar_estoque_form/', views.atualizar_estoque_form_view, name='atualizar_estoque_form'),
	path('api/', include(router.urls)),

]

ERP/ERP/urls.py
from CRUD.views import AssetViewSet
from django.contrib import admin
from django.urls import path, include 
from . import views # Import do arquivo que contém as URLs do projeto ERP
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register('assets', AssetViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home_view), 
    path('estoque/', views.estoque_view, name='estoque'), 
    path('CRUD/', include('CRUD.urls', namespace='CRUD'))


    #path('CRUD/', include(router.urls)),  # Incluindo as URLs da API REST
    #path('CRUD/', include('CRUD.urls')),  # Incluindo as URLs do CRUD

]

# Em TRABALHO_2_ERP/ERP/urls.py (ou o urls.py principal do seu projeto)

ERP/templates/FrontEnd/adicionar-estoque.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Adicionar Estoque</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}"> 
</head>
<body>

   <div class="container">
        <div class ="side-left">
        <h1 class="style1"> Aplicações </h1>

            <div class="menu">
                <div class="links"><a href="/"Home>Home</a></div>
                <div class="links"><a href="{% url  'estoque' %}">Estoque</a></div>
                <div class="links"><a href="#">Vendas</a></div>
                <div class="links"><a href="#">Compras</a></div>
                <div class="links"> <a href="#">Financeiro</a></div>
                <div class="links"> <a href="#">Relatórios</a></div>
                <div class="links"> <a href="#">Clientes</a></div>
            </div>
        </div>

        <div class="side-right">
            <h2 class="style3">Bem vindo(a) ao sistema de estoque</h2>
            
            <div class="form-box">
                
                <form action="" method="post" >{% csrf_token %}
            
                    <input type="text" name="name" placeholder="Digite o nome do item" required>
                    <input type="number" name="quantity" placeholder="Digite a quantidade" required>
                    <input type="text" name="description" placeholder="Digite a descrição do item" required>
                    <input type="text" name="category" placeholder="Digite a categoria do item" required>
                    
                    <button type="submit">Cadastrar</button>
                </form>
            </div>
            
           
        </div>
    </div>


   
    
</body>
</html>

ERP/templates/FrontEnd/consultar-estoque.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Consultar Estoque</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}"> 
</head>
<body>

   <div class="container">
        <div class ="side-left">
        <h1 class="style1"> Aplicações </h1>

            <div class="menu">
                <div class="links"><a href="/"Home>Home</a></div>
                <div class="links"><a href="{% url  'estoque' %}">Estoque</a></div>
                <div class="links"><a href="#">Vendas</a></div>
                <div class="links"><a href="#">Compras</a></div>
                <div class="links"> <a href="#">Financeiro</a></div>
                <div class="links"> <a href="#">Relatórios</a></div>
                <div class="links"> <a href="#">Clientes</a></div>
            </div>
        </div>

        <div class = "side-right">
            <table>
                <thead>
                    <tr>
                        <th>Item</th>
                        <th>Quantidade</th>
                        <th>Descrição</th>
                        <th>Categoria</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in items %}
                    <tr>
                        <td>{{ item.name }}</td>
                        <td>{{ item.quantity }}</td>
                        <td>{{ item.descri }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <!-- <div class="side-right">
            <div class="form-box">
                <h2 class="style3">Bem vindo(a) ao sistema de estoque</h2>
                <form action="">
                    <input type="text" name="item" placeholder="Digite o nome do item" required>
                    <button type="submit">Pesquisar</button>
                </form>
            </div>
            
           
        </div> -->
    </div>


   
    
</body>
</html>

ERP/templates/FrontEnd/estoque.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Estoque</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}"> 
</head>
<body>

   <div class="container">
        <div class ="side-left">
        <h1 class="style1"> Aplicações </h1>

            <div class="menu">
                <div class="links"><a href="/"Home>Home</a></div>
                <div class="links"><a href="{% url  'estoque' %}">Estoque</a></div>
                <div class="links"><a href="#">Vendas</a></div>
                <div class="links"><a href="#">Compras</a></div>
                <div class="links"> <a href="#">Financeiro</a></div>
                <div class="links"> <a href="#">Relatórios</a></div>
                <div class="links"> <a href="#">Clientes</a></div>
            </div>
        </div>

        <div class="side-right">
            
                <h2 class="style3">Bem vindo(a) ao sistema de estoque</h2>
                <h2 class="style4"> Escolha o que deseja fazer: </h2>
            

            <div class="menu">
                <div class="style4"><a href="{% url 'CRUD:consultar_estoque' %}">Consultar estoque</a></div>
                <div class="style4"><a href="{% url 'CRUD:adicionar_estoque' %}">Adicionar item</a></div>
                <div class="style4"><a href="{% url 'CRUD:remover_estoque' %}">Remover item</a></div>
                <div class="style4"><a href="{% url 'CRUD:atualizar_estoque' %}">Editar item</a></div>
                
                
            </div>
           
        </div>
    </div>


   
    
</body>
</html>

ERP/templates/FrontEnd/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}"> 
</head>
<body>

   <div class="container">
        <div class ="side-left">
        <h1 class="style1"> Aplicações </h1>

            <div class="menu">
                <div class="links"><a href="/"Home>Home</a></div>
                <div class="links"><a href="{% url  'estoque' %}">Estoque</a></div>
                <div class="links"><a href="#">Vendas</a></div>
                <div class="links"><a href="#">Compras</a></div>
                <div class="links"> <a href="#">Financeiro</a></div>
                <div class="links"> <a href="#">Relatórios</a></div>
                <div class="links"> <a href="#">Clientes</a></div>
            </div>
        </div>

        <div class="side-right">
            <h1 class="style2">Sistema de Planejamento de Recursos Empresariais</h1>
           
        </div>
    </div>


   
    
</body>
</html>